### ISSUE TITLE
TACS hook fails to apply on 1.17.1

### ISSUE THREAD

**Issue by KJP12** [arthurbambou/Server-Translations#16]
<details><summary>Full crash report</summary>

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/9/21, 2:02 PM
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at net.gudenau.minecraft.asm.impl.MixinTransformer.lambda$transformClassBytes$3(MixinTransformer.java:126)
	at net.gudenau.minecraft.asm.impl.MixinTransformer.cache(MixinTransformer.java:212)
	at net.gudenau.minecraft.asm.impl.MixinTransformer.transformClassBytes(MixinTransformer.java:113)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_3215.<init>(class_3215.java:87)
	at net.minecraft.class_3218.<init>(class_3218.java:200)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:383)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350)
	at net.minecraft.class_3176.method_3823(class_3176.java:184)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method translated_reloadData(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String; in server_translations.mixin.json:MixinThreadedAnvilChunkStorage failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Server-Translations-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-1048-azure
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 1553989632 bytes (1482 MiB) / 2495610880 bytes (2380 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 1
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Hyper-V virtual VGA
	Graphics card #0 vendor: Microsoft Corporation (0x1414)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x5353
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8006.96
	Virtual memory used (MB): 3847.95
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 10 total; -Xmx8G -Xms512M -Xss512K -XX:+UseZGC -XX:MaxInlineLevel=25 -XX:MaxInlineSize=75 -XX:FreqInlineSize=512 -XX:+AlwaysPreTouch -XX:+FlightRecorder -XX:StartFlightRecording=disk=true,dumponexit=true,maxage=2h,maxsize=1g,name=the-glitch,settings=/home/kjp12/The-Glitch.jfc
	Fabric Mods: 
		armor-stand-editor: Armor Stand Editor 1.3.1+1.17.1
		carpet: Carpet Mod 1.4.43
		com_atlassian_commonmark_commonmark: commonmark 0.15.2
		com_atlassian_commonmark_commonmark-ext-autolink: commonmark-ext-autolink 0.15.2
		com_atlassian_commonmark_commonmark-ext-gfm-strikethrough: commonmark-ext-gfm-strikethrough 0.15.2
		com_h2database_h2: h2 1.4.200
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		crude-entity-eviction: Crude Entity Eviction 0.0.0+mc.1.17.1
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab612113
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		golfiv: Golf IV 0.3.2
		gud_asm: gudASM 0.2.10
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lazydfu: LazyDFU 0.1.2
		ledger: Ledger 1.0.2
		lithium: Lithium 0.7.3
		luckperms: LuckPerms 5.3.51
		markdown_chat: Markdown Chat 1.1.0
		minecraft: Minecraft 1.17.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_nibor_autolink_autolink: autolink 0.10.0
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		plymouth: Plymouth: Utilities 0.0.0-beta.5+mc.1.17-pre4
		plymouth-anti-xray: Plymouth: Anti-Xray 0.0.0-beta.5+mc.1.17-pre4
		plymouth-common: Plymouth: Common 0.0.0-beta.6+mc.1.17-pre4
		plymouth-locking: Plymouth: Locking 0.0.0-beta.5+mc.1.17-pre4
		server_translations: Server Translations 1.4.5+1.17.1
		server_translations_api: Server Translations API 1.4.5+1.17.1
		sgui: SGui 1.0.0-rc3-1.17.1
		spaceserve-config: SpaceServe Config API 0.2.0
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		ticktools: TickTools 1.0.0
		wires: Wires 1.0.3
	Player Count: 0 / 1024; []
	Data Packs: vanilla (incompatible), Fabric Mods, file/Alternate Bedrock Breaking (incompatible), file/CavesAndCliffsPreview.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

</details>

What I can say on the local repository is that removing the TACS hook doesn't seem to affect it at all, so it might be safe to remove as is.

**Comment by KJP12** [comment]
Closing as stale and seems to have no known reproduction outside of here anyways?

If it crops up again, feel free to reopen.
